# Generated by Django 4.0.3 on 2022-04-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_options_alter_color_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.RemoveField(
            model_name='variants',
            name='size',
        ),
        migrations.AddField(
            model_name='variants',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, to='shop.size'),
        ),
    ]
