# Generated by Django 4.0.3 on 2022-04-15 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_name_remove_variants_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='minamount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='image_id',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='size',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.AlterField(
            model_name='images',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.doortype'),
        ),
    ]
