# Generated by Django 4.0.3 on 2022-04-15 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_variants_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='images',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.images'),
        ),
    ]
