# Generated by Django 4.0.3 on 2022-04-15 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_variants_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='image_id',
        ),
    ]
