# Generated by Django 4.0.3 on 2022-04-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_sizes_alter_category_options_alter_color_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizes',
            options={'verbose_name': 'Размер', 'verbose_name_plural': '7. Размеры'},
        ),
        migrations.RemoveField(
            model_name='doortype',
            name='price',
        ),
        migrations.AlterField(
            model_name='sizes',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
