# Generated by Django 4.0.3 on 2022-04-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_sizes_options_remove_doortype_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doortype',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
