# Generated by Django 4.0.3 on 2022-04-15 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_brand_product_brand_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Детальная фото',
                'verbose_name_plural': '5. Детальные фото',
            },
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Фотография вида двери', 'verbose_name_plural': '5. Фотографии видов дверей'},
        ),
        migrations.AddField(
            model_name='product',
            name='related_images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.relatedimages'),
        ),
    ]
