# Generated by Django 4.0.3 on 2022-04-15 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_variants_sale_percent_variants_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='sale_percent',
        ),
    ]
