# Generated by Django 4.0.3 on 2022-04-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_variants_sale_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='type',
            field=models.CharField(blank=True, choices=[('ДО', 'ДО'), ('ДГ', 'ДГ')], max_length=10, null=True),
        ),
    ]
