# Generated by Django 4.0.3 on 2022-04-17 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_remove_images_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='images/banners/')),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Цвет', 'verbose_name_plural': '7. Цвета'},
        ),
        migrations.AlterModelOptions(
            name='relatedimages',
            options={'verbose_name': 'Детальная фото', 'verbose_name_plural': '6. Детальные фото'},
        ),
        migrations.AlterModelOptions(
            name='sizes',
            options={'verbose_name': 'Размер', 'verbose_name_plural': '9. Размеры'},
        ),
        migrations.AlterField(
            model_name='variants',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.color', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='images',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='sale_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Цена по Скидке'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='size',
            field=models.ManyToManyField(to='shop.sizes', verbose_name='Размеры'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.doortype', verbose_name='Тип'),
        ),
    ]
