# Generated by Django 4.0.3 on 2022-04-17 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_banner_alter_color_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '0. Баннер', 'verbose_name_plural': '0. Баннеры'},
        ),
    ]
