# Generated by Django 4.0.3 on 2022-04-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_banner_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': '2. Бренды'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Цвет', 'verbose_name_plural': '8. Цвета'},
        ),
        migrations.AlterModelOptions(
            name='doortype',
            options={'verbose_name': 'Тип двери', 'verbose_name_plural': '5. Типы двери'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Фотография вида двери', 'verbose_name_plural': '6. Фотографии видов дверей'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Дверь', 'verbose_name_plural': '3. Двери'},
        ),
        migrations.AlterModelOptions(
            name='relatedimages',
            options={'verbose_name': 'Детальная фото', 'verbose_name_plural': '7. Детальные фото'},
        ),
        migrations.AlterModelOptions(
            name='sizes',
            options={'verbose_name': 'Размер', 'verbose_name_plural': '10. Размеры'},
        ),
        migrations.AlterModelOptions(
            name='variants',
            options={'verbose_name': 'Вариант', 'verbose_name_plural': '4. Варианты'},
        ),
    ]
