# Generated by Django 4.0.3 on 2022-04-18 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_brand_options_alter_color_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizes',
            options={'verbose_name': 'Размер', 'verbose_name_plural': '9. Размеры'},
        ),
    ]
