# Generated by Django 4.0.3 on 2022-04-18 09:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Спецификация'),
        ),
    ]
