# Generated by Django 4.0.3 on 2022-04-18 10:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_product_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=ckeditor.fields.RichTextField(blank=True, default='\n    <table class="table">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t<h5>Модель</h5>\n\t\t\t</td>\n\t\t\t<td>\n\t\t\t<h5>БЕРЛОГА- 80</h5>\n\t\t\t</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t<h5>Толщина полотна</h5>\n\t\t\t</td>\n\t\t\t<td>\n\t\t\t<h5>80мм</h5>\n\t\t\t</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t<h5>Контуры уплотнения</h5>\n\t\t\t</td>\n\t\t\t<td>\n\t\t\t<h5>2</h5>\n\t\t\t</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t<h5>Отделка внутри</h5>\n\t\t\t</td>\n\t\t\t<td>\n\t\t\t<h5>МДФ панепь 16мм</h5>\n\t\t\t</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t<h5>Покрытие</h5>\n\t\t\t</td>\n\t\t\t<td>\n\t\t\t<h5>ПВХ – Пленка</h5>\n\t\t\t</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t<h5>Размеры</h5>\n\t\t\t</td>\n\t\t\t<td>\n\t\t\t<h5>970 Х 2050мм / 860 Х 2050мм</h5>\n\t\t\t</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t<h5>Утеплитель</h5>\n\t\t\t</td>\n\t\t\t<td>\n\t\t\t<h5>Пенополистирол</h5>\n\t\t\t</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t<h5>Замки и фурнитура</h5>\n\t\t\t</td>\n\t\t\t<td>\n\t\t\t<h5>верхний «Border» (сувальдный)</h5>\n\t\t\t</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t<h5>нижний</h5>\n\t\t\t</td>\n\t\t\t<td>\n\t\t\t<h5>«Argus» А512 [цилиндровый)</h5>\n\t\t\t</td>\n\t\t</tr>\n\t</tbody>\n</table>', null=True, verbose_name='Спецификация'),
        ),
    ]
