# Generated by Django 4.0.3 on 2022-04-18 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_country_remove_brand_country_product_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна Производства', 'verbose_name_plural': '10. Страны Производства'},
        ),
    ]
