# Generated by Django 4.0.3 on 2022-04-18 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_alter_country_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='detail',
        ),
    ]
