# Generated by Django 4.0.3 on 2022-04-18 17:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_alter_product_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=ckeditor.fields.RichTextField(blank=True, default='\n    <table class="table">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t<h5>Модель</h5>\n\t\t\t</td>\n\t\t\t<td>\n\t\t\t<h5>&nbsp;Лео</h5>\n\t\t\t</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t<p>Высота полотен</p>\n\t\t\t</td>\n\t\t\t<td>\n\t\t\t<h5>2000мм</h5>\n\t\t\t</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t<p>Ширина</p>\n\t\t\t</td>\n\t\t\t<td>\n\t\t\t<h5>600,700,800,900 мм</h5>\n\t\t\t</td>\n\t\t</tr>\n\t</tbody>\n</table>\n', null=True, verbose_name='Спецификация'),
        ),
    ]
