# Generated by Django 4.0.3 on 2022-04-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_alter_product_specification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='images',
        ),
        migrations.AddField(
            model_name='variants',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Фото'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
