# Generated by Django 4.0.3 on 2022-04-19 16:30

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_alter_variants_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('services', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Сервисы')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.service'),
        ),
    ]
