# Generated by Django 4.0.3 on 2022-05-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='comment',
            field=models.TextField(max_length=250),
        ),
    ]
