# Generated by Django 4.0.3 on 2022-05-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_alter_productreview_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
