# Generated by Django 4.0.3 on 2022-05-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_alter_productreview_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='comment',
            field=models.TextField(max_length=250, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rate',
            field=models.IntegerField(default=1, verbose_name='Оценка'),
        ),
    ]
