# Generated by Django 4.0.3 on 2022-05-08 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_likedproducts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна Производства', 'verbose_name_plural': 'Страны Производства'},
        ),
        migrations.AlterModelOptions(
            name='doortype',
            options={'verbose_name': 'Тип двери', 'verbose_name_plural': 'Типы двери'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Дверь', 'verbose_name_plural': 'Двери'},
        ),
        migrations.AlterModelOptions(
            name='relatedimages',
            options={'verbose_name': 'Детальная фото', 'verbose_name_plural': 'Детальные фото'},
        ),
        migrations.AlterModelOptions(
            name='sizes',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.AlterModelOptions(
            name='variants',
            options={'verbose_name': 'Вариант', 'verbose_name_plural': 'Варианты'},
        ),
    ]
