# Generated by Django 4.0.3 on 2022-05-08 19:31

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_question_created_at_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
